variables:
- name: Configuration
  value: Release
- name: PackageOutputPath
  value: $(Build.ArtifactStagingDirectory)

stages:

- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'windows-2019'
    steps:
    - checkout: self
      submodules: recursive
      clean: true

    - task: UseDotNet@2
      inputs:
        version: 2.1.x
        packageType: sdk
        performMultiLevelLookup: true

    - task: UseDotNet@2
      inputs:
        version: 3.1.x
        packageType: sdk
        performMultiLevelLookup: true

    - task: UseDotNet@2
      inputs:
        packageType: sdk
        useGlobalJson: true
        performMultiLevelLookup: true

    - script: dotnet restore -p:Configuration=$(Configuration)
      displayName: Restore

    - script: dotnet build --no-restore -m:1 -p:Configuration=$(Configuration)
      displayName: Build

    - script: dotnet test --no-restore -p:Configuration=$(Configuration)
      displayName: Test

    - task: PublishBuildArtifacts@1
      displayName: Upload
      condition: succeeded()
      inputs:
        PathtoPublish: $(Build.ArtifactStagingDirectory)
        ArtifactName: package
        ArtifactType: Container
